File=open("health.txt","w")
File.write("Healthcare TechnologyMy project is about Making healthcare accessible to almost everyone on the planet.\nThis can be made possible through certain ways which includes Technology.\nTechnology has made a lot of things /activities/information possible and accessible by people even in healthcare.\nHealthCare in Africa  is lagging with a lot of gaps.\nThis might be due to wrong diagnosis\nLack of adequate doctors,\nLow ratio of patients to doctors,\n Rural and inadequate number of hospitals.\nThis has been going on for a while and I believe that Technology can solve these problems.That is why I am so interested in Creating a software app.\nPluto Health is a software app that would be involved in filling a lot of gaps in the healthcare system in Africa,as it would be built based on the Collaboration of different Stakeholders such as \nHospital Owners,\nDoctors,\nNurses,Patients,\nInsurance Companies among others.\nPluto app would have different sections dedicated to different stakeholders.\nOne for Hospitals,One for Private Doctors,\nOne for the patients \n One for insurance Companies.\nThe patients would be able to connect to the other stakeholders using this app.\nThe Patients would be able to access a Doctor on Demand,Book an appointment,Pick an insurance Scheme,register with Hospitals among other features.Features that would benefit the Patients\nE-prescription,\nDaily Monitoring for patients with Chronic disease\n,Accessibility to patient files.\nThe Hospital can register patients under their Companies and link them with an insurance company of their Choices,also send them ambulances for an urgent case regardless of their registered hospitals among other features.")
File.close()

Classes=open("Class.txt","w")
Classes.write("Classes\nHospitals\nPrivate Doctors\nPatients\nSubclasses(Hospital)\nDoctors\nNurses\nInsurance Companies")
Classes.close()

Instance=open("Instance.txt","w")
Instance.write("Hospital\n,def innit(self,Name,Location,Registration,Ownership(private or Public),Insurance,Number of doctors,Number of Nurses,ratings)\n Private Doctors \n def innit(self,Name,ID,Qualification,gender,Clinic of work,Clinic ID,ratings)\nPatients\ndef innit(self,Name,Age,Gender,Identification Number, Nationality,Occupation)\nHospital\ndef Add patient(self)\ninput(Kindly enter your name\n input(Kindly enter your Age\ninput(Kindly enter your nationality)\ninput(Do you have an insurance scheme\nif answer== yes\nKindly enter the name\nIf answer==No\ninput(Would you like to register under our insurance\n if answer==Yes\nprint List.insurance\nif answer==No\n print(You would be based on pay as you use \n print(You have been added to our patient list\nprint(Your ID is 001\n def remove()\ninput(Why do you want to terminate our services with you)\nprint(Thanks for believing in us\n print(Our services are always available\n def doctor List\n For X,y in Doctor,Print x,y\n def Services offered\nprint(Service.list)    \nprivate doctor\n def private doctors() \ninput(What iS Your name)\ninput(Your job ID)\ninput(Your qualifications)\ninput(Your clinic of work)\nNew Doctor=Private Doctor(Name,Qualification,ID,Rating\n Patients\n def Private patient\ninput(Kindly enter your name)\ninput(Kindly enter your age\ninput(Kindly enter your ID number)\ninput(Kindly enter your Occupation)\ninput(Kindly enter your nationality)\nNew patient=Patient(Name,age,Occupation)\n def Ambulance()\ninput(Kindly enter your street Number)\nprint(You will be connected to hospitals close to you Hospital\nTest scenario for class hospital\nTesting for Valid registraion\nValid Registration:Combination of Number and Figures for Id\nCheck what happens when Valid Registration:Combination of Number and Figures for Id \nExpected resultA100\n Testing for the ownership:It must It must be in letters either public or private\n.Test for number of nurses:It must be numeric\n The Location of the hospital must include two words reply which includes city,State\n Class: Private Doctor\nTest Case 1:Checking for the Id number\nIt must be a combination of numeric and figures\nTest for name:It must be only letters\n Test for Clinic ID:It must consist of Numeric and letters\nTest for gender:It should be written in one letter,M or F\nTest for ratings:It must be written in one figure\nclass Patients\nTest for name:It must be in letters\nTest for gender:It must be written in one letter which is either M or F\n Test for age:It must be numeric\nTest for nationality:It mst be in letters\n")
Instance.close()
Test=open("Test.txt","w")
Test.write("Hospital\nTest scenario for class hospital\nTesting for Valid registraion\nValid Registration:Combination of Number and Figures for Id\nCheck what happens when a Valid Id is put in:A100\nExpected result:An Id is accepted\n Testing for the ownership:It must be either public or private.\nTest for number of doctors:It must be in numeric\n.Test for number of nurses\n:It must be numeric\n The Location of the hospital must include two words reply which includes city,State ")